# test
# application.yml
server:
  port: 0
  servlet:
    context-path: /scheduler
  message:
    basename: messages
  forward-headers-strategy: framework
#  port: ${random.int(10000,51000)}

spring:
  application:
    name: sj-lab-scheduler
  task:
    scheduling:
      enabled: true
  datasource:
    url: jdbc:postgresql://211.188.62.54:30017/sjlab
    username: stylealist
    password: "!@xogml159"
    driver-class-name: org.postgresql.Driver  # URL로 자동판별되지만 명시해도 OK

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  level:
    org.springframework: info
    root: info
# 추후 보안에 맞게 설정해야 함
management:
  endpoints:
    web:
      exposure:
        include: "self,health"

apikey:  # 외부 연동 API 키 모음
  safe: ISGUSHVA-ISGU-ISGU-ISGU-ISGUSHVA5T  # 생활안전정보 API
  apis: # 공공 데이터포털
    busInfo: o9zW2lZLR06hqlpgGQSjOTtf3jfGdFdrtrxwBM%2FshNmdqU%2Btzasq46ZYQasDYVW43Bs%2BxAXwgmBdxYjH5NLE4Q%3D%3D # 국토교통부_(TAGO)_버스노선정보